name: uuid
version: 0.6
date: 2018-09-22
description: |
    RFC 4122 UUIDs

authors:
    - name: Markus Pfeiffer
      url: http://www.morphism.de/~markusp/

maintainers:
    - name: Markus Pfeiffer
      url: http://www.morphism.de/~markusp/

GAP: ">= 4.8"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/uuid/
readme: README.md
packageinfo: https://gap-packages.github.io/uuid/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/uuid/releases/download/v0.6/uuid-0.6.tar.gz

abstract: |
    UUIDs for GAP

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
